config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :widget_attrs
  resources :pages
  resources :texts
  resources :pictures
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/widget_attr.rb
class WidgetAttr < ApplicationRecord
  belongs_to :widget
end

app/controllers/widget_attrs_controller.rb
class WidgetAttrsController < ApplicationController
  before_action :set_widget_attr, only: [:show, :edit, :update, :destroy]

  # GET /widget_attrs
  # GET /widget_attrs.json
  def index
    @widget_attrs = WidgetAttr.all
  end

  # GET /widget_attrs/1
  # GET /widget_attrs/1.json
  def show
  end

  # GET /widget_attrs/new
  def new
    @widget_attr = WidgetAttr.new
  end

  # GET /widget_attrs/1/edit
  def edit
  end

  # POST /widget_attrs
  # POST /widget_attrs.json
  def create
    @widget_attr = WidgetAttr.new(widget_attr_params)

    respond_to do |format|
      if @widget_attr.save
        format.html { redirect_to @widget_attr, notice: 'Widget attr was successfully created.' }
        format.json { render :show, status: :created, location: @widget_attr }
      else
        format.html { render :new }
        format.json { render json: @widget_attr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widget_attrs/1
  # PATCH/PUT /widget_attrs/1.json
  def update
    respond_to do |format|
      if @widget_attr.update(widget_attr_params)
        format.html { redirect_to @widget_attr, notice: 'Widget attr was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget_attr }
      else
        format.html { render :edit }
        format.json { render json: @widget_attr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widget_attrs/1
  # DELETE /widget_attrs/1.json
  def destroy
    @widget_attr.destroy
    respond_to do |format|
      format.html { redirect_to widget_attrs_url, notice: 'Widget attr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget_attr
      @widget_attr = WidgetAttr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_attr_params
      params.require(:widget_attr).permit(:windget_id, :name, :value, :type)
    end
end

app/helpers/widget_attrs_helper.rb
module WidgetAttrsHelper
end

app/views/widget_attrs/_form.html.erb
<%= form_for(widget_attr) do |f| %>
  <% if widget_attr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(widget_attr.errors.count, "error") %> prohibited this widget_attr from being saved:</h2>

      <ul>
      <% widget_attr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :windget_id %>
    <%= f.text_field :windget_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.number_field :type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widget_attrs/edit.html.erb
<h1>Editing Widget Attr</h1>

<%= render 'form', widget_attr: @widget_attr %>

<%= link_to 'Show', @widget_attr %> |
<%= link_to 'Back', widget_attrs_path %>

app/views/widget_attrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Widget Attrs</h1>

<table>
  <thead>
    <tr>
      <th>Windget</th>
      <th>Name</th>
      <th>Value</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widget_attrs.each do |widget_attr| %>
      <tr>
        <td><%= widget_attr.windget %></td>
        <td><%= widget_attr.name %></td>
        <td><%= widget_attr.value %></td>
        <td><%= widget_attr.type %></td>
        <td><%= link_to 'Show', widget_attr %></td>
        <td><%= link_to 'Edit', edit_widget_attr_path(widget_attr) %></td>
        <td><%= link_to 'Destroy', widget_attr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget Attr', new_widget_attr_path %>

app/views/widget_attrs/new.html.erb
<h1>New Widget Attr</h1>

<%= render 'form', widget_attr: @widget_attr %>

<%= link_to 'Back', widget_attrs_path %>

app/views/widget_attrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Windget:</strong>
  <%= @widget_attr.windget %>
</p>

<p>
  <strong>Name:</strong>
  <%= @widget_attr.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @widget_attr.value %>
</p>

<p>
  <strong>Type:</strong>
  <%= @widget_attr.type %>
</p>

<%= link_to 'Edit', edit_widget_attr_path(@widget_attr) %> |
<%= link_to 'Back', widget_attrs_path %>